export const KNOWN_RULE_IMPLEMENTATION_KEYS = [
  'RULE_NODO0_ELIGIBILITY',
  'RULE_ACADEMIC_GRADES_BLOCKER',
  'RULE_NODO15_MYSTERY_SHOPPER',
  'RULE_NODO11_OPERATIONAL_CANCELLATION',
  'RULE_NODO13_DECISION_35',
  'RULE_NODO13_DECISION_53',
  'RULE_NODO10_SALES_PROMISE',
  'RULE_NODO9_ENROLLMENT_ERROR',
  'RULE_NODO8_CYCLE_CHANGE',
  'RULE_NODO7_UNREACHABLE',
  'RULE_NODO6_EFFECTIVE_CONTACT',
  'RULE_NODO1_DATES',
  'RULE_NODO5_STUDENT_REQUEST',
  'RULE_NODO16_RETENTION',
  'RULE_NODO14_DOCUMENTATION',
] as const;

export type RuleImplementationKey = typeof KNOWN_RULE_IMPLEMENTATION_KEYS[number];

export function isKnownRuleImplementationKey(value: string): value is RuleImplementationKey {
  return (KNOWN_RULE_IMPLEMENTATION_KEYS as readonly string[]).includes(value);
}
